### ISSUE TITLE
Launch failed with ruby-1.9.3

### ISSUE THREAD

**Issue by bondar-pavel** [dotdoom/rpi-tank-rack#2]
Tested with ruby 1.9.3 ruby on rvm.
However startup was successful with ruby 2.0.0.
Should we document somewhere such behaviour?

```
[apostal@alarmpi rpi-tank-rack]$ ./launch
Using rack adapter
/home/apostal/git/rpi-tank-rack/config.ru:1:in `require_relative': cannot infer basepath (LoadError)
        from /home/apostal/git/rpi-tank-rack/config.ru:1:in `block in <main>'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
        from /home/apostal/git/rpi-tank-rack/config.ru:1:in `new'
        from /home/apostal/git/rpi-tank-rack/config.ru:1:in `<main>'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.1/lib/rack/adapter/loader.rb:33:in `eval'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.1/lib/rack/adapter/loader.rb:33:in `load'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.1/lib/rack/adapter/loader.rb:42:in `for'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.1/lib/thin/controllers/controller.rb:170:in `load_adapter'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.1/lib/thin/controllers/controller.rb:74:in `start'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.1/lib/thin/runner.rb:200:in `run_command'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.1/lib/thin/runner.rb:156:in `run!'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.1/bin/thin:6:in `<top (required)>'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/bin/thin:23:in `load'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/bin/thin:23:in `<main>'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
        from /home/apostal/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by bondar-pavel** [comment]
Yahoo! :+1:
